# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
MagicItem.create(name: "Alchemy Jug", tp: "4")
MagicItem.create(name: "Bag of Beans", tp: "4")
MagicItem.create(name: "Bag of Holding", tp: "4")
MagicItem.create(name: "Balance of Harmony", tp: "4")
MagicItem.create(name: "Bead of Force", tp: "4")
MagicItem.create(name: "Cap of Water Breathing", tp: "4")
MagicItem.create(name: "Chime of Opening", tp: "4")
MagicItem.create(name: "Cloak of the Manta Ray", tp: "4")
MagicItem.create(name: "Decanter of Endless Water", tp: "4")
MagicItem.create(name: "Driftglobe", tp: "4")
MagicItem.create(name: "Dust of Disappearance", tp: "4")
MagicItem.create(name: "Dust of Dryness", tp: "4")
MagicItem.create(name: "Dust of Sneezing and Choking", tp: "4")
MagicItem.create(name: "Elemental Gem", tp: "4")
MagicItem.create(name: "Eyes of Minute Seeing", tp: "4")
MagicItem.create(name: "Folding Boat", tp: "4")
MagicItem.create(name: "Goggles of Night", tp: "4")
MagicItem.create(name: "Helm of Comprehending Languages", tp: "4")
MagicItem.create(name: "Heward's Handy Haversack", tp: "4")
MagicItem.create(name: "Horseshoes of Speed", tp: "4")
MagicItem.create(name: "Immovable Rod", tp: "4")
MagicItem.create(name: "Lantern of Revealing", tp: "4")
MagicItem.create(name: "Mirror of the Past", tp: "4")
MagicItem.create(name: "Periapt of Health", tp: "4")
MagicItem.create(name: "Quall's Feather Token", tp: "4")
MagicItem.create(name: "Ring of Swimming", tp: "4")
MagicItem.create(name: "Robe of Serpents", tp: "4")
MagicItem.create(name: "Robe of Useful Items", tp: "4")
MagicItem.create(name: "Rope of Climbing", tp: "4")
MagicItem.create(name: "Saddle of the Cavalier", tp: "4")
MagicItem.create(name: "Sending Stones", tp: "4")
MagicItem.create(name: "Wand of Magic Detection", tp: "4")
MagicItem.create(name: "Wand of Secrets", tp: "4")
MagicItem.create(name: "Adamantine Armor (Chain Mail)", tp: "8")
MagicItem.create(name: "Adamantine Armor (Chain Shirt)", tp: "8")
MagicItem.create(name: "Adamantine Armor (Scale Mail)", tp: "8")
MagicItem.create(name: "Amulet of Proof Against Detection and Location", tp: "8")
MagicItem.create(name: "Bag of Tricks (Gray)", tp: "8")
MagicItem.create(name: "Bag of Tricks (Rust)", tp: "8")
MagicItem.create(name: "Bag of Tricks (Tan)", tp: "8")
MagicItem.create(name: "Boots of Elvenkind", tp: "8")
MagicItem.create(name: "Boots of Winterlands", tp: "8")
MagicItem.create(name: "Bracers of Archery", tp: "8")
MagicItem.create(name: "Brooch of Shielding", tp: "8")
MagicItem.create(name: "Circlet of Blasting", tp: "8")
MagicItem.create(name: "Cloak of Elvenkind", tp: "8")
MagicItem.create(name: "Cloak of Protection", tp: "8")
MagicItem.create(name: "Deck of Illusions", tp: "8")
MagicItem.create(name: "Eversmoking Bottle", tp: "8")
MagicItem.create(name: "Eyes of Charming", tp: "8")
MagicItem.create(name: "Eyes of the Eagle", tp: "8")
MagicItem.create(name: "Figurine of Wondrous Power, Silver Raven", tp: "8")
MagicItem.create(name: "Gauntlets of Ogre Power", tp: "8")
MagicItem.create(name: "Gem of Brightness", tp: "8")
MagicItem.create(name: "Gloves of Missile Snaring", tp: "8")
MagicItem.create(name: "Gloves of Swimming and Climbing", tp: "8")
MagicItem.create(name: "Gloves of Thievery", tp: "8")
MagicItem.create(name: "Hat of Disguise", tp: "8")
MagicItem.create(name: "Headband of Intellect", tp: "8")
MagicItem.create(name: "Helm of Telepathy", tp: "8")
MagicItem.create(name: "Insignia of Claws", tp: "8")
MagicItem.create(name: "Instrument of the Bards (Doss Lute)", tp: "8")
MagicItem.create(name: "Instrument of the Bards (Fochlucan Bandore)", tp: "8")
MagicItem.create(name: "Instrument of the Bards (Mac-Fuimidh Cittern)", tp: "8")
MagicItem.create(name: "Javelin of Lightning", tp: "8")
MagicItem.create(name: "Mariner's Armor (Chain Shirt)", tp: "8")
MagicItem.create(name: "Mariner's Armor (Scale Mail)", tp: "8")
MagicItem.create(name: "Necklace of Adaptation", tp: "8")
MagicItem.create(name: "Pearl of Power", tp: "8")
MagicItem.create(name: "Periapt of Wound Closure", tp: "8")
MagicItem.create(name: "Pipes of Haunting", tp: "8")
MagicItem.create(name: "Pipes of the Sewers", tp: "8")
MagicItem.create(name: "Quiver of Ehlonna", tp: "8")
MagicItem.create(name: "Ring of Jumping", tp: "8")
MagicItem.create(name: "Ring of Mind Shielding", tp: "8")
MagicItem.create(name: "Ring of Warmth", tp: "8")
MagicItem.create(name: "Ring of Water Walking", tp: "8")
MagicItem.create(name: "Rod of the Pact Keeper, +1", tp: "8")
MagicItem.create(name: "Sentinel Shield", tp: "8")
MagicItem.create(name: "Shatterspike", tp: "8")
MagicItem.create(name: "Shield, +1", tp: "8")
MagicItem.create(name: "Slippers of Spider Climbing", tp: "8")
MagicItem.create(name: "Spider Staff", tp: "8")
MagicItem.create(name: "Staff of Defense", tp: "8")
MagicItem.create(name: "Staff of the Adder", tp: "8")
MagicItem.create(name: "Stone of Good Luck", tp: "8")
MagicItem.create(name: "Trident of Fish Command", tp: "8")
MagicItem.create(name: "Wand of Entangle", tp: "8")
MagicItem.create(name: "Wand of Magic Missiles", tp: "8")
MagicItem.create(name: "Wand of the War Mage, +1", tp: "8")
MagicItem.create(name: "Wand of Web", tp: "8")
MagicItem.create(name: "Weapon of Warning", tp: "8")
MagicItem.create(name: "Weapon of Warning", tp: "8")
MagicItem.create(name: "Weapon, +1", tp: "8")
MagicItem.create(name: "Wind Fan", tp: "8")
MagicItem.create(name: "Bag of Devouring", tp: "8")
MagicItem.create(name: "Horseshoes of a Zephyr", tp: "8")
MagicItem.create(name: "Night Caller", tp: "8")
MagicItem.create(name: "Nolzur's Marvelous Pigments", tp: "8")
MagicItem.create(name: "Portable Hole", tp: "8")
MagicItem.create(name: "Stonespeaker Crystal", tp: "8")
MagicItem.create(name: "Adamantine Armor (Breastplate)", tp: "10")
MagicItem.create(name: "Adamantine Armor (Splint)", tp: "10")
MagicItem.create(name: "Amulet of Health", tp: "10")
MagicItem.create(name: "Armor, +1 Chain Mail", tp: "10")
MagicItem.create(name: "Armor, +1 Chain Shirt", tp: "10")
MagicItem.create(name: "Armor, +1 Leather", tp: "10")
MagicItem.create(name: "Armor, +1 Scale Mail", tp: "10")
MagicItem.create(name: "Armor, +1 Spiked", tp: "10")
MagicItem.create(name: "Armor of Resistance (Chain Mail)", tp: "10")
MagicItem.create(name: "Armor of Resistance (Chain Shirt)", tp: "10")
MagicItem.create(name: "Armor of Resistance (Leather)", tp: "10")
MagicItem.create(name: "Armor of Resistance (Scale Mail)", tp: "10")
MagicItem.create(name: "Arrow-Catching Shield", tp: "10")
MagicItem.create(name: "Belt of Dwarvenkind", tp: "10")
MagicItem.create(name: "Belt of Hill Giant Strength", tp: "10")
MagicItem.create(name: "Blood Spear", tp: "10")
MagicItem.create(name: "Boots of Levitation", tp: "10")
MagicItem.create(name: "Boots of Speed", tp: "10")
MagicItem.create(name: "Bowl of Commanding Water Elementals", tp: "10")
MagicItem.create(name: "Bracers of Defense", tp: "10")
MagicItem.create(name: "Brazier of Commanding Fire Elementals", tp: "10")
MagicItem.create(name: "Cape of the Mountebank", tp: "10")
MagicItem.create(name: "Censer of Controlling Air Elementals", tp: "10")
MagicItem.create(name: "Claws of the Umberhulk", tp: "10")
MagicItem.create(name: "Cloak of the Bat", tp: "10")
MagicItem.create(name: "Dagger of Venom", tp: "10")
MagicItem.create(name: "Dimensional Shackles", tp: "10")
MagicItem.create(name: "Dragon Slayer", tp: "10")
MagicItem.create(name: "Dragontooth Dagger", tp: "10")
MagicItem.create(name: "Elven Chain", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Bronze Griffon", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Ebony Fly", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Golden Lions", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Ivory Goats", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Marble Elephant", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Onyx Dog", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Serpentine Owl", tp: "10")
MagicItem.create(name: "Flame Tongue Sword", tp: "10")
MagicItem.create(name: "Gem of Seeing", tp: "10")
MagicItem.create(name: "Giant Slayer", tp: "10")
MagicItem.create(name: "Horn of Blasting", tp: "10")
MagicItem.create(name: "Instrument of the Bards (Canaith Mandolin)", tp: "10")
MagicItem.create(name: "Instrument of the Bards (Cli Lyre)", tp: "10")
MagicItem.create(name: "Ioun Stone (Awareness)", tp: "10")
MagicItem.create(name: "Ioun Stone (Protection)", tp: "10")
MagicItem.create(name: "Ioun Stone (Sustenance)", tp: "10")
MagicItem.create(name: "Iron Bands of Bilarro", tp: "10")
MagicItem.create(name: "Mace of Disruption", tp: "10")
MagicItem.create(name: "Mace of Smiting", tp: "10")
MagicItem.create(name: "Mace of Terror", tp: "10")
MagicItem.create(name: "Mariner's Armor (Breastplate)", tp: "10")
MagicItem.create(name: "Mariner's Armor (Splint)", tp: "10")
MagicItem.create(name: "Mithral Armor (Breastplate)", tp: "10")
MagicItem.create(name: "Mithral Armor (Splint)", tp: "10")
MagicItem.create(name: "Necklace of Prayer Beads", tp: "10")
MagicItem.create(name: "Periapt of Proof Against Poison", tp: "10")
MagicItem.create(name: "Ring of Animal Influence", tp: "10")
MagicItem.create(name: "Ring of Evasion", tp: "10")
MagicItem.create(name: "Ring of Feather Falling", tp: "10")
MagicItem.create(name: "Ring of Free Action", tp: "10")
MagicItem.create(name: "Ring of Protection", tp: "10")
MagicItem.create(name: "Ring of Resistance", tp: "10")
MagicItem.create(name: "Ring of the Ram", tp: "10")
MagicItem.create(name: "Ring of X-Ray Vision", tp: "10")
MagicItem.create(name: "Robe of Eyes", tp: "10")
MagicItem.create(name: "Rod of Rulership", tp: "10")
MagicItem.create(name: "Rod of the Pact Keeper, +2", tp: "10")
MagicItem.create(name: "Rope of Entanglement", tp: "10")
MagicItem.create(name: "Shield of Missile Attraction", tp: "10")
MagicItem.create(name: "Shield, +2", tp: "10")
MagicItem.create(name: "Staff of Charming", tp: "10")
MagicItem.create(name: "Staff of Healing", tp: "10")
MagicItem.create(name: "Staff of Swarming Insects", tp: "10")
MagicItem.create(name: "Staff of the Python", tp: "10")
MagicItem.create(name: "Staff of the Woodlands", tp: "10")
MagicItem.create(name: "Staff of Withering", tp: "10")
MagicItem.create(name: "Stone of Controlling Earth Elementals", tp: "10")
MagicItem.create(name: "Sword of Life Stealing", tp: "10")
MagicItem.create(name: "Sword of Wounding", tp: "10")
MagicItem.create(name: "Tentacle Rod", tp: "10")
MagicItem.create(name: "Vicious Weapon", tp: "10")
MagicItem.create(name: "Wand of Binding", tp: "10")
MagicItem.create(name: "Wand of Enemy Detection", tp: "10")
MagicItem.create(name: "Wand of Fear", tp: "10")
MagicItem.create(name: "Wand of Fireballs", tp: "10")
MagicItem.create(name: "Wand of Lightning Bolts", tp: "10")
MagicItem.create(name: "Wand of Paralysis", tp: "10")
MagicItem.create(name: "Wand of the War Mage, +2", tp: "10")
MagicItem.create(name: "Wand of Wonder", tp: "10")
MagicItem.create(name: "Weapon, +2", tp: "10")
MagicItem.create(name: "Wings of Flying", tp: "10")
MagicItem.create(name: "Adamantine Armor (Half Plate)", tp: "10")
MagicItem.create(name: "Adamantine Armor (Plate)", tp: "10")
MagicItem.create(name: "Animated Shield", tp: "10")
MagicItem.create(name: "Armor, +1 Breastplate", tp: "10")
MagicItem.create(name: "Armor, +1 Splint", tp: "10")
MagicItem.create(name: "Armor, +1 Studded Leather", tp: "10")
MagicItem.create(name: "Armor of Resistance (Breastplate)", tp: "10")
MagicItem.create(name: "Armor of Resistance (Splint)", tp: "10")
MagicItem.create(name: "Armor of Resistance (Studded Leather)", tp: "10")
MagicItem.create(name: "Belt of Frost Giant Strength", tp: "10")
MagicItem.create(name: "Belt of Stone Giant Strength", tp: "10")
MagicItem.create(name: "Cloak of Arachnida", tp: "10")
MagicItem.create(name: "Cloak of Displacement", tp: "10")
MagicItem.create(name: "Crystal Ball (Very Rare)", tp: "10")
MagicItem.create(name: "Dancing Sword", tp: "10")
MagicItem.create(name: "Dragon Scale Mail", tp: "10")
MagicItem.create(name: "Dwarven Thrower", tp: "10")
MagicItem.create(name: "Eagle Whistle", tp: "10")
MagicItem.create(name: "Figurine of Wondrous Power, Obsidian Steed", tp: "10")
MagicItem.create(name: "Frost Brand", tp: "10")
MagicItem.create(name: "Glamoured Studded Leather", tp: "10")
MagicItem.create(name: "Helm of Brilliance", tp: "10")
MagicItem.create(name: "Instrument of the Bards (Anstruth Harp)", tp: "10")
MagicItem.create(name: "Ioun Stone (Absorption)", tp: "10")
MagicItem.create(name: "Ioun Stone (Agility)", tp: "10")
MagicItem.create(name: "Ioun Stone (Fortitude)", tp: "10")
MagicItem.create(name: "Ioun Stone (Insight)", tp: "10")
MagicItem.create(name: "Ioun Stone (Intellect)", tp: "10")
MagicItem.create(name: "Ioun Stone (Leadership)", tp: "10")
MagicItem.create(name: "Ioun Stone (Strength)", tp: "10")
MagicItem.create(name: "Ioun Stone (Strength)", tp: "10")
MagicItem.create(name: "Mantle of Spell Resistance", tp: "10")
MagicItem.create(name: "Manual of Bodily Health", tp: "10")
MagicItem.create(name: "Manual of Gainful Exercise", tp: "10")
MagicItem.create(name: "Manual of Golems", tp: "10")
MagicItem.create(name: "Manual of Quickness of Action", tp: "10")
MagicItem.create(name: "Mariner's Armor (Half Plate)", tp: "10")
MagicItem.create(name: "Mariner's Armor (Plate)", tp: "10")
MagicItem.create(name: "Mirror of Life Trapping", tp: "10")
MagicItem.create(name: "Mithral Armor (Half Plate)", tp: "10")
MagicItem.create(name: "Mithral Armor (Plate)", tp: "10")
MagicItem.create(name: "Nine Lives Stealer", tp: "10")
MagicItem.create(name: "Oathbow", tp: "10")
MagicItem.create(name: "Ring of Regeneration", tp: "10")
MagicItem.create(name: "Ring of Shooting Stars", tp: "10")
MagicItem.create(name: "Ring of Telekinesis", tp: "10")
MagicItem.create(name: "Robe of Scintillating Colors", tp: "10")
MagicItem.create(name: "Rod of Absorption", tp: "10")
MagicItem.create(name: "Rod of Alertness", tp: "10")
MagicItem.create(name: "Rod of Security", tp: "10")
MagicItem.create(name: "Rod of the Pact Keeper, +3", tp: "10")
MagicItem.create(name: "Scimitar of Speed", tp: "10")
MagicItem.create(name: "Shield, +3", tp: "10")
MagicItem.create(name: "Spellguard Shield", tp: "10")
MagicItem.create(name: "Staff of Fire", tp: "10")
MagicItem.create(name: "Staff of Frost", tp: "10")
MagicItem.create(name: "Staff of Power", tp: "10")
MagicItem.create(name: "Staff of Striking", tp: "10")
MagicItem.create(name: "Staff of Thunder and Lightning", tp: "10")
MagicItem.create(name: "Sun Blade", tp: "10")
MagicItem.create(name: "Sword of Sharpness", tp: "10")
MagicItem.create(name: "Tome of Clear Thought", tp: "10")
MagicItem.create(name: "Tome of Leadership and Influence", tp: "10")
MagicItem.create(name: "Tome of Understanding", tp: "10")
MagicItem.create(name: "Wand of Polymorph", tp: "10")
MagicItem.create(name: "Wand of the War Mage, +3", tp: "10")
MagicItem.create(name: "Weapon, +3", tp: "10")
MagicItem.create(name: "Winged Boots", tp: "10")
MagicItem.create(name: "Armor, +1 Half Plate", tp: "12")
MagicItem.create(name: "Armor, +1 Plate", tp: "12")
MagicItem.create(name: "Armor of Resistance (Half Plate)", tp: "12")
MagicItem.create(name: "Belt of Fire Giant Strength", tp: "12")
MagicItem.create(name: "Broom of Flying", tp: "12")
MagicItem.create(name: "Instrument of the Bards (Ollamh Harp)", tp: "12")
MagicItem.create(name: "Plate Armor of Etherealness", tp: "12")
MagicItem.create(name: "Plate Armor of Resistance", tp: "12")
MagicItem.create(name: "Ring of Invisibility", tp: "12")
MagicItem.create(name: "Ring of Spell Turning", tp: "12")
MagicItem.create(name: "Scorpion Armor", tp: "12")
MagicItem.create(name: "Armor, +3 Breastplate", tp: "14")
MagicItem.create(name: "Armor, +3 Chain Shirt", tp: "14")
MagicItem.create(name: "Armor, +3 Half Plate", tp: "14")
MagicItem.create(name: "Armor, +3 Leather", tp: "14")
MagicItem.create(name: "Armor, +3 Plate", tp: "14")
MagicItem.create(name: "Armor, +3 Spiked", tp: "14")
MagicItem.create(name: "Armor, +3 Splint", tp: "14")
MagicItem.create(name: "Armor, +3 Studded Leather", tp: "14")
MagicItem.create(name: "Armor of Invulnerability", tp: "14")
MagicItem.create(name: "Belt of Cloud Giant Strength", tp: "14")
MagicItem.create(name: "Belt of Storm Giant Strength", tp: "14")
MagicItem.create(name: "BookMark", tp: "14")
MagicItem.create(name: "Carpet of Flying", tp: "14")
MagicItem.create(name: "Cloak of Invisibility", tp: "14")
MagicItem.create(name: "Crystal Ball of Mind Reading", tp: "14")
MagicItem.create(name: "Crystal Ball of Telepathy", tp: "14")
MagicItem.create(name: "Crystal Ball of True Seeing", tp: "14")
MagicItem.create(name: "Defender", tp: "14")
MagicItem.create(name: "Dwarven Plate", tp: "14")
MagicItem.create(name: "Efreeti Chain", tp: "14")
MagicItem.create(name: "Hazirawn", tp: "14")
MagicItem.create(name: "Hammer of Thunderbolts", tp: "14")
MagicItem.create(name: "Holy Avenger", tp: "14")
MagicItem.create(name: "Holy Symbol of Ravenkind", tp: "14")
MagicItem.create(name: "Icon of Ravenloft", tp: "14")
MagicItem.create(name: "Ioun Stone (Greater Absorption)", tp: "14")
MagicItem.create(name: "Ioun Stone (Mastery)", tp: "14")
MagicItem.create(name: "Ioun Stone (Regeneration)", tp: "14")
MagicItem.create(name: "Lost Crown of Besilmer", tp: "14")
MagicItem.create(name: "Orcsplitter", tp: "14")
MagicItem.create(name: "Ring of Air Elemental Command", tp: "14")
MagicItem.create(name: "Ring of Djinni Summoning", tp: "14")
MagicItem.create(name: "Ring of Earth Elemental Command", tp: "14")
MagicItem.create(name: "Ring of Fire Elemental Command", tp: "14")
MagicItem.create(name: "Ring of Water Elemental Command", tp: "14")
MagicItem.create(name: "Robe of the Archmagi", tp: "14")
MagicItem.create(name: "Robe of Stars", tp: "14")
MagicItem.create(name: "Rod of Resurrection", tp: "14")
MagicItem.create(name: "Scarab of Protection", tp: "14")
MagicItem.create(name: "Staff of the Magi", tp: "14")
MagicItem.create(name: "Vorpal Sword", tp: "14")
MagicItem.create(name: "Waythe", tp: "14")
Item.create(name: "Potion of Healing", cost: "50")
Item.create(name: "Potion of Climbing", cost: "75")
Item.create(name: "Potion of Animal Friendship", cost: "100")
Item.create(name: "Potion of Greater Healing", cost: "100")
Item.create(name: "Potion of Water Breathing", cost: "100")
Item.create(name: "Potion of Superior Healing", cost: "500")
Item.create(name: "Potion of Supreme Healing", cost: "5000")
Item.create(name: "Potion of Invisibility", cost: "5000")
Item.create(name: "Cantrip Spell Scroll", cost: "25")
Item.create(name: "1st Level Spell Scroll", cost: "75")
Item.create(name: "2nd Level Spell Scroll", cost: "150")
Item.create(name: "3rd Level Spell Scroll", cost: "300")
Item.create(name: "4th Level Spell Scroll", cost: "500")
Item.create(name: "5th Level Spell Scroll", cost: "1000")
Item.create(name: "Abacus", cost: "2")
Item.create(name: "Acid (vial)", cost: "25")
Item.create(name: "Alchemist's Fire (flask)", cost: "50")
Item.create(name: "Antitoxin", cost: "50")
Item.create(name: "Backpack", cost: "2")
Item.create(name: "Ball Bearing", cost: "0.001")
Item.create(name: "Ball Bearings (Bag of 1000)", cost: "1")
Item.create(name: "Barrel", cost: "2")
Item.create(name: "Basket", cost: "0.4")
Item.create(name: "Bedroll", cost: "1")
Item.create(name: "Bell", cost: "1")
Item.create(name: "Blanket", cost: "0.5")
Item.create(name: "Block and Tackle", cost: "1")
Item.create(name: "Book", cost: "25")
Item.create(name: "Bucket", cost: "0.05")
Item.create(name: "Bullseye Lantern", cost: "10")
Item.create(name: "Burglar's Pack", cost: "16")
Item.create(name: "Caltrops", cost: "0.05")
Item.create(name: "Caltrops (20)", cost: "1")
Item.create(name: "Candle", cost: "0.001")
Item.create(name: "Chain (10 feet)", cost: "0.05")
Item.create(name: "Chalk (1 piece)", cost: "0.01")
Item.create(name: "Chest", cost: "5")
Item.create(name: "Climber's Kit", cost: "25")
Item.create(name: "Common Clothes", cost: "0.5")
Item.create(name: "Component Pouch", cost: "25")
Item.create(name: "Costume Clothes", cost: "5")
Item.create(name: "Crossbow Bolt Case", cost: "1")
Item.create(name: "Crowbar", cost: "2")
Item.create(name: "Diplomat's Pack", cost: "39")
Item.create(name: "Dungeoneer's Pack", cost: "12")
Item.create(name: "Entertainer's Pack", cost: "40")
Item.create(name: "Explorer's Pack", cost: "10")
Item.create(name: "Fine Clothes", cost: "15")
Item.create(name: "Fishing Tackle", cost: "1")
Item.create(name: "Flask", cost: "0.001")
Item.create(name: "Glass Bottle", cost: "2")
Item.create(name: "Hammer", cost: "1")
Item.create(name: "Healer's Kit", cost: "5")
Item.create(name: "Hempen Rope (50 feet)", cost: "1")
Item.create(name: "Holy Water (flask)", cost: "25")
Item.create(name: "Hooded Lantern", cost: "5")
Item.create(name: "Hourglass", cost: "25")
Item.create(name: "Hunting Trap", cost: "5")
Item.create(name: "Ink (1 ounce bottle)", cost: "10")
Item.create(name: "Ink Pen", cost: "0.002")
Item.create(name: "Iron Pot", cost: "2")
Item.create(name: "Iron Spikes", cost: "0.1")
Item.create(name: "Iron Spikes (10)", cost: "1")
Item.create(name: "Jug", cost: "0.02")
Item.create(name: "Ladder (10 feet)", cost: "0.1")
Item.create(name: "Lamp", cost: "0.5")
Item.create(name: "Lock", cost: "10")
Item.create(name: "Magnifying Glass", cost: "100")
Item.create(name: "Manacles", cost: "2")
Item.create(name: "Map or Scroll Case", cost: "1")
Item.create(name: "Merchant's Scale", cost: "5")
Item.create(name: "Mess Kit", cost: "0.2")
Item.create(name: "Miner's Pick", cost: "2")
Item.create(name: "Oil (flask)", cost: "0.1")
Item.create(name: "Paper (one sheet)", cost: "0.2")
Item.create(name: "Parchment (one sheet)", cost: "0.1")
Item.create(name: "Perfume (vial)", cost: "5")
Item.create(name: "Pitcher", cost: "0.002")
Item.create(name: "Piton", cost: "0.005")
Item.create(name: "Pole (10 feet)", cost: "0.05")
Item.create(name: "Portable Ram", cost: "4")
Item.create(name: "Pouch", cost: "0.5")
Item.create(name: "Priest's Pack", cost: "19")
Item.create(name: "Quiver", cost: "1")
Item.create(name: "Rations (1 day)", cost: "0.5")
Item.create(name: "Robes", cost: "1")
Item.create(name: "Sack", cost: "0.001")
Item.create(name: "Scholar's Pack", cost: "40")
Item.create(name: "Sealing Wax", cost: "0.5")
Item.create(name: "Shovel", cost: "2")
Item.create(name: "Signal Whistle", cost: "0.05")
Item.create(name: "Signet Ring", cost: "5")
Item.create(name: "Silk Rope (50 feet)", cost: "10")
Item.create(name: "Sledge Hammer", cost: "2")
Item.create(name: "Soap", cost: "0.002")
Item.create(name: "Spellbook", cost: "50")
Item.create(name: "Spyglass", cost: "1000")
Item.create(name: "Steel Mirror", cost: "5")
Item.create(name: "Tankard", cost: "0.01")
Item.create(name: "Tinderbox", cost: "0.5")
Item.create(name: "Torch", cost: "0.01")
Item.create(name: "Traveler's Clothes", cost: "2")
Item.create(name: "Two-Person Tent", cost: "2")
Item.create(name: "Vial", cost: "1")
Item.create(name: "Waterskin", cost: "0.2")
Item.create(name: "Whetstone", cost: "0.01")
Item.create(name: "Assassin's Blood (Ingested)", cost: "150")
Item.create(name: "Basic Poison (vial)", cost: "100")
Item.create(name: "Burnt Othur Fumes (Inhaled)", cost: "500")
Item.create(name: "Carrion Crawler Mucus (Contact)", cost: "200")
Item.create(name: "Drow Poison (Injury)", cost: "200")
Item.create(name: "Essence of Ether (Inhaled)", cost: "300")
Item.create(name: "Malice (Inhaled)", cost: "250")
Item.create(name: "Midnight Tears (Ingested)", cost: "1500")
Item.create(name: "Oil of Taggit (Contact)", cost: "400")
Item.create(name: "Pale Tincture (Ingested)", cost: "250")
Item.create(name: "Purple Worm Poison (Injury)", cost: "2000")
Item.create(name: "Serpent Venom (Injury)", cost: "200")
Item.create(name: "Torpor (Injested)", cost: "600")
Item.create(name: "Truth Serum (Injested)", cost: "150")
Item.create(name: "Wyvern Poison (Injury)", cost: "1200")
Item.create(name: "Arrow", cost: "0.05")
Item.create(name: "Arrows (20)", cost: "1")
Item.create(name: "Blowgun Needle", cost: "0.02")
Item.create(name: "Blowgun Needles (50)", cost: "1")
Item.create(name: "Crossbow Bolt", cost: "0.05")
Item.create(name: "Crossbow Bolts (20)", cost: "1")
Item.create(name: "Sling Bullet", cost: "0.002")
Item.create(name: "Sling Bullets (20)", cost: "0.04")
Item.create(name: "Alchemist's Supplies", cost: "50")
Item.create(name: "Brewer's Supplies", cost: "20")
Item.create(name: "Calligrapher's Supplies", cost: "10")
Item.create(name: "Carpenter's Tools", cost: "8")
Item.create(name: "Cartographer's Tools", cost: "15")
Item.create(name: "Cobbler's Tools", cost: "5")
Item.create(name: "Cook's Utensils", cost: "1")
Item.create(name: "Glassblower's Tools", cost: "30")
Item.create(name: "Jewler's Tools", cost: "25")
Item.create(name: "Leatherworker's Tools", cost: "5")
Item.create(name: "Mason's Tools", cost: "10")
Item.create(name: "Painter's Supplies", cost: "10")
Item.create(name: "Potter's Tools", cost: "10")
Item.create(name: "Smith's Tools", cost: "20")
Item.create(name: "Tinker's Tools", cost: "50")
Item.create(name: "Weaver's Tools", cost: "1")
Item.create(name: "Woodcarver's Tools", cost: "1")
Item.create(name: "Dice Set", cost: "0.1")
Item.create(name: "Dragonchess Set", cost: "1")
Item.create(name: "Playing Card Set", cost: "0.5")
Item.create(name: "Three-Dragon Ante Set", cost: "1")
Item.create(name: "Silvering Weapon", cost: "100")
Item.create(name: "Silvering Ammunition (10)", cost: "100")
Item.create(name: "Chain Mail", cost: "75")
Item.create(name: "Plate Armor", cost: "1500")
Item.create(name: "Ring Mail", cost: "30")
Item.create(name: "Splint Armor", cost: "200")
Item.create(name: "Breastplate", cost: "400")
Item.create(name: "Chain Shirt", cost: "50")
Item.create(name: "Half Plate Armor", cost: "750")
Item.create(name: "Hide Armor", cost: "10")
Item.create(name: "Scale Mail", cost: "50")
Item.create(name: "Leather Armor", cost: "10")
Item.create(name: "Padded Armor", cost: "5")
Item.create(name: "Studded Leather Armor", cost: "45")
Item.create(name: "Shield", cost: "10")
Item.create(name: "Club", cost: "0.1")
Item.create(name: "Dagger", cost: "2")
Item.create(name: "Greatclub", cost: "0.2")
Item.create(name: "Handaxe", cost: "5")
Item.create(name: "Javelin", cost: "0.2")
Item.create(name: "Light Hammer", cost: "2")
Item.create(name: "Mace", cost: "5")
Item.create(name: "Quarterstaff", cost: "0.2")
Item.create(name: "Sickle", cost: "1")
Item.create(name: "Spear", cost: "1")
Item.create(name: "Dart", cost: "0.05")
Item.create(name: "Light Crossbow", cost: "25")
Item.create(name: "Sling", cost: "0.1")
Item.create(name: "Battleaxe", cost: "10")
Item.create(name: "Flail", cost: "10")
Item.create(name: "Glaive", cost: "20")
Item.create(name: "Greataxe", cost: "30")
Item.create(name: "Greatsword", cost: "50")
Item.create(name: "Halberd", cost: "20")
Item.create(name: "Lance", cost: "10")
Item.create(name: "Longsword", cost: "15")
Item.create(name: "Maul", cost: "10")
Item.create(name: "Morningstar", cost: "15")
Item.create(name: "Pike", cost: "5")
Item.create(name: "Rapier", cost: "25")
Item.create(name: "Scimitar", cost: "25")
Item.create(name: "Shortsword", cost: "10")
Item.create(name: "Trident", cost: "5")
Item.create(name: "War Pick", cost: "5")
Item.create(name: "Warhammer", cost: "15")
Item.create(name: "Whip", cost: "2")
Item.create(name: "Blowgun", cost: "10")
Item.create(name: "Hand Crossbow", cost: "75")
Item.create(name: "Heavy Crossbow", cost: "50")
Item.create(name: "Longbow", cost: "50")
Item.create(name: "Net", cost: "1")
Item.create(name: "Bagpipes", cost: "30")
Item.create(name: "Drum", cost: "6")
Item.create(name: "Dulcimer", cost: "25")
Item.create(name: "Flute", cost: "2")
Item.create(name: "Horn", cost: "3")
Item.create(name: "Lute", cost: "35")
Item.create(name: "Lyre", cost: "30")
Item.create(name: "Pan Flute", cost: "12")
Item.create(name: "Shawm", cost: "2")
Item.create(name: "Viol", cost: "30")
Item.create(name: "Camel", cost: "50")
Item.create(name: "Donkey", cost: "8")
Item.create(name: "Draft Horse", cost: "50")
Item.create(name: "Elephant", cost: "200")
Item.create(name: "Mastiff", cost: "25")
Item.create(name: "Mule", cost: "8")
Item.create(name: "Pony", cost: "30")
Item.create(name: "Riding Horse", cost: "75")
Item.create(name: "Warhorse", cost: "400")
Item.create(name: "Amulet", cost: "5")
Item.create(name: "Crystal", cost: "10")
Item.create(name: "Emblem", cost: "5")
Item.create(name: "Orb", cost: "25")
Item.create(name: "Reliquary", cost: "5")
Item.create(name: "Rod", cost: "10")
Item.create(name: "Sprig of Mistletoe", cost: "1")
Item.create(name: "Totem", cost: "1")
Item.create(name: "Wand", cost: "10")
Item.create(name: "Yew Wand", cost: "10")
Item.create(name: "Staff", cost: "5")
Item.create(name: "Wooden Staff", cost: "5")
Item.create(name: "Barding", cost: "x4")
Item.create(name: "Bit and Bridle", cost: "2")
Item.create(name: "Exotic Saddle", cost: "60")
Item.create(name: "Military Saddle", cost: "20")
Item.create(name: "Pack Saddle", cost: "5")
Item.create(name: "Riding Saddle", cost: "10")
Item.create(name: "Saddlebags", cost: "4")
Item.create(name: "Disguise Kit", cost: "25")
Item.create(name: "Forgery Kit", cost: "15")
Item.create(name: "Herbalism Kit", cost: "5")
Item.create(name: "Navigator's Tools", cost: "25")
Item.create(name: "Poisoner's Kit", cost: "50")
Item.create(name: "Thieves' Tools", cost: "25")
Item.create(name: "Airship", cost: "20000")
Item.create(name: "Carriage", cost: "100")
Item.create(name: "Cart", cost: "15")
Item.create(name: "Chariot", cost: "250")
Item.create(name: "Galley", cost: "30000")
Item.create(name: "Keelboat", cost: "3000")
Item.create(name: "Longship", cost: "10000")
Item.create(name: "Rowboat", cost: "50")
Item.create(name: "Sailing Ship", cost: "10000")
Item.create(name: "Sled", cost: "20")
Item.create(name: "Wagon", cost: "35")
Item.create(name: "Warship", cost: "25000")
